import {createSeed,declarations} from './seed.js';
export {createSeed};
export const nowOf=s=>Date.now()+(s.clockOffset||0);
export const stamp=s=>new Date(nowOf(s)).toISOString();
export const uid=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36)}`;
const need=(ok,message)=>{if(!ok)throw new Error(message);};
export const ageAt=(dob,at=Date.now())=>{const d=new Date(dob),n=new Date(at);if(!dob||Number.isNaN(+d))return 0;return n.getUTCFullYear()-d.getUTCFullYear()-(n.getUTCMonth()<d.getUTCMonth()||n.getUTCMonth()===d.getUTCMonth()&&n.getUTCDate()<d.getUTCDate()?1:0);};
export const publicPets=s=>s.pets.filter(p=>!p.deletedAt&&p.approval==='APPROVED'&&p.visibility!=='HIDDEN');
export const petAgeMonths=(p,at=Date.now())=>p.birthDate?Math.max(0,Math.floor((at-new Date(p.birthDate))/2629800000)):Number(p.ageMonths||0)+Math.max(0,Math.floor((at-new Date(p.ageRecordedAt||at))/2629800000));
const effectiveScopes=(s,user)=>s.moderation.filter(m=>m.userId===user.id&&m.action==='RESTRICT'&&!m.revokedAt&&(!m.endsAt||+new Date(m.endsAt)>nowOf(s))).flatMap(m=>m.scopes||[]);
export function canWrite(s,user,scope){return !!user&&user.status!=='BANNED'&&!(user.status==='RESTRICTED'&&effectiveScopes(s,user).includes(scope));}
export function isParty(s,user,a){return !!user&&(user.role==='ADMIN'||a.applicantId===user.id||s.pets.find(p=>p.id===a.petId)?.posterId===user.id);}
export function canApply(s,user,p){if(!user)return 'Bạn cần đăng nhập để gửi đơn.';if(!canWrite(s,user,'application'))return 'Tài khoản đang bị hạn chế nhận nuôi.';if(ageAt(user.dob,nowOf(s))<18)return 'Người nhận nuôi phải đủ 18 tuổi.';if(user.verified!=='VERIFIED')return 'Vui lòng hoàn tất xác minh danh tính.';if(!p||p.approval!=='APPROVED'||p.deletedAt||p.visibility==='HIDDEN')return 'Bài thú cưng chưa mở công khai.';if(!['WAITING','UNDER_REVIEW'].includes(p.status))return 'Thú cưng hiện chưa tiếp nhận đơn.';if(p.posterId===user.id)return 'Bạn không thể nhận nuôi thú cưng do mình đăng.';if(s.applications.some(a=>a.petId===p.id&&a.applicantId===user.id&&['PENDING','INTERVIEW','BACKUP','APPROVED'].includes(a.status)))return 'Bạn đã có một hồ sơ còn hiệu lực cho thú cưng này.';return '';}
export function publicStats(s){const pets=s.pets.filter(p=>!p.deletedAt);return {total:pets.length,adopted:pets.filter(p=>p.status==='ADOPTED').length,dogs:pets.filter(p=>p.status==='ADOPTED'&&p.species==='DOG').length,cats:pets.filter(p=>p.status==='ADOPTED'&&p.species==='CAT').length,applications:s.applications.length,waiting:pets.filter(p=>p.status==='WAITING').length};}
const cleanLog=value=>{if(!value)return null;const out={};for(const key of ['id','status','approval','visibility','name','title','petId','applicationId','action','reason','rating','type','role'])if(value[key]!==undefined)out[key]=value[key];return out;};
function log(s,actor,action,entity,id,oldValue,newValue){s.logs.unshift({id:uid('log'),actorId:actor?.id||null,action,entity,entityId:id,oldValue:cleanLog(oldValue),newValue:cleanLog(newValue),createdAt:stamp(s),ip:'local',userAgent:typeof navigator==='undefined'?'Node test':navigator.userAgent});}
function notify(s,userId,type,title,body,route,key){if(!userId||s.notifications.some(n=>n.dedupeKey===key))return;s.notifications.unshift({id:uid('n'),userId,type,title,body,route,readAt:null,createdAt:stamp(s),dedupeKey:key||uid('event')});}
const admins=s=>s.users.filter(u=>u.role==='ADMIN'&&u.status!=='BANNED');
function notifyParties(s,a,type,title,body,route){const p=s.pets.find(p=>p.id===a.petId);for(const id of new Set([p?.posterId,a.applicantId]))notify(s,id,type,title,body,route,uid('event'));}
function recalcPet(s,p){if(['ADOPTED','PAUSED','COMING_SOON'].includes(p.status))return;p.status=s.applications.some(a=>a.petId===p.id&&['PENDING','INTERVIEW','BACKUP'].includes(a.status))?'UNDER_REVIEW':'WAITING';}
function cancelRelated(s,a){for(const ap of s.appointments.filter(ap=>ap.applicationId===a.id&&ap.status==='SCHEDULED'))ap.status='CANCELLED';const cm=s.commitments.find(c=>c.applicationId===a.id);if(cm&&cm.status!=='CANCELLED'){cm.status='CANCELLED';cm.cancelledAt=stamp(s);}const h=s.handovers.find(h=>h.applicationId===a.id);if(h&&h.status!=='COMPLETED')h.status='CANCELLED';}
function text(p,key,label,max=5000){const v=String(p[key]??'').trim();need(v,`Vui lòng nhập ${label}.`);need(v.length<=max,`${label} quá dài.`);return v;}

/** Pure state transition boundary for a LOCAL frontend demonstration, not a security server. */
export function command(state,actorId,type,payload={}){
 const s=structuredClone(state),p=payload,actor=s.users.find(u=>u.id===actorId);let result;
 const auth=scope=>{need(actor,'Vui lòng đăng nhập.');need(canWrite(s,actor,scope),'Tài khoản không có quyền thực hiện thao tác này.');};
 const admin=()=>{auth('admin');need(actor.role==='ADMIN','Chỉ quản trị viên được thực hiện thao tác này.');};
 const ownedPet=id=>{const pet=s.pets.find(x=>x.id===id&&!x.deletedAt);need(pet,'Không tìm thấy thú cưng.');need(actor&&(pet.posterId===actor.id||actor.role==='ADMIN'),'Bạn không có quyền quản lý bài đăng này.');return pet;};
 const app=id=>{const a=s.applications.find(x=>x.id===id);need(a,'Không tìm thấy đơn nhận nuôi.');need(isParty(s,actor,a),'Bạn không có quyền xem hồ sơ này.');return a;};
 const poster=a=>{need(s.pets.find(x=>x.id===a.petId)?.posterId===actor?.id||actor?.role==='ADMIN','Chỉ người đăng thú cưng được xét hồ sơ này.');};
 const mutate=(entity,item,changes,action=type)=>{const old=structuredClone(item);Object.assign(item,changes,{updatedAt:stamp(s)});log(s,actor,action,entity,item.id,old,item);result=item.id;};
 switch(type){
 case 'REGISTER':{
   const email=text(p,'email','email').toLowerCase(),phone=text(p,'phone','số điện thoại');need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Email chưa đúng định dạng.');need(/^\+?[0-9\s]{9,15}$/.test(phone),'Số điện thoại chưa hợp lệ.');need(!s.users.some(u=>u.email===email||u.phone===phone),'Email hoặc số điện thoại đã được sử dụng.');need(p.terms,'Bạn cần đồng ý điều khoản.');need(p.dob&&+new Date(p.dob)<nowOf(s),'Ngày sinh chưa hợp lệ.');need(p.passwordHash,'Thiếu mật khẩu.');
   const u={id:uid('u'),name:text(p,'name','họ tên',100),email,phone,dob:p.dob,city:text(p,'city','tỉnh/thành phố'),address:text(p,'address','địa chỉ'),occupation:text(p,'occupation','nghề nghiệp'),role:'USER',status:'ACTIVE',verified:'UNVERIFIED',passwordHash:p.passwordHash,createdAt:stamp(s),termsAcceptedAt:stamp(s)};s.users.push(u);result=u.id;notify(s,u.id,'REGISTER','Chào mừng đến với Petcare','Hồ sơ của bạn đã được tạo. Hãy xác minh để sẵn sàng nhận nuôi.','profile',uid('registered'));log(s,u,'REGISTER','USER',u.id,null,u);break;}
 case 'LOGIN':{need(actor&&actor.status!=='BANNED','Tài khoản đã bị khóa.');actor.lastLoginAt=stamp(s);log(s,actor,'LOGIN','USER',actor.id,null,{id:actor.id});break;}
 case 'LOGOUT':{if(actor)log(s,actor,'LOGOUT','USER',actor.id,null,{id:actor.id});break;}
 case 'PROFILE':{auth('profile');const email=text(p,'email','email').toLowerCase(),phone=text(p,'phone','số điện thoại');need(!s.users.some(u=>u.id!==actor.id&&(u.email===email||u.phone===phone)),'Email hoặc điện thoại đã tồn tại.');need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Email chưa hợp lệ.');need(/^\+?[0-9\s]{9,15}$/.test(phone),'Số điện thoại chưa hợp lệ.');need(p.dob&&+new Date(p.dob)<nowOf(s),'Ngày sinh chưa hợp lệ.');const identityChanged=actor.name!==p.name||actor.dob!==p.dob;mutate('USER',actor,{name:text(p,'name','họ tên'),email,phone,dob:p.dob,city:p.city,address:text(p,'address','địa chỉ'),occupation:text(p,'occupation','nghề nghiệp'),bio:p.bio||'',verified:identityChanged?'UNVERIFIED':actor.verified});break;}
 case 'PASSWORD':{auth('profile');need(p.passwordHash,'Thiếu mật khẩu mới.');actor.passwordHash=p.passwordHash;log(s,actor,'CHANGE_PASSWORD','USER',actor.id,null,{id:actor.id});break;}
 case 'IDENTITY_SUBMIT':{auth('identity');need(p.documents?.length,'Hãy đính kèm ít nhất một giấy tờ mẫu.');need(actor.verified!=='PENDING','Hồ sơ của bạn đang được xét duyệt.');const v={id:uid('iv'),userId:actor.id,fullName:text(p,'fullName','họ tên trên giấy tờ'),citizenId:text(p,'citizenId','mã giấy tờ mẫu'),documents:p.documents,status:'PENDING',createdAt:stamp(s),reason:''};s.identities.push(v);actor.verified='PENDING';result=v.id;admins(s).forEach(u=>notify(s,u.id,'IDENTITY','Có hồ sơ xác minh mới',`${actor.name} vừa gửi hồ sơ mẫu.`,'admin/identities',uid('event')));log(s,actor,type,'IDENTITY',v.id,null,{id:v.id,status:v.status});break;}
 case 'IDENTITY_REVIEW':{admin();const v=s.identities.find(x=>x.id===p.id);need(v&&v.status==='PENDING','Hồ sơ không còn chờ duyệt.');need(['VERIFIED','FAILED'].includes(p.status),'Trạng thái không hợp lệ.');if(p.status==='FAILED')text(p,'reason','lý do từ chối');mutate('IDENTITY',v,{status:p.status,reason:p.reason||'',reviewedBy:actor.id,reviewedAt:stamp(s)});s.users.find(u=>u.id===v.userId).verified=p.status;notify(s,v.userId,'IDENTITY',p.status==='VERIFIED'?'Danh tính đã được xác minh':'Hồ sơ cần bổ sung',p.reason||'Bạn đã có thể gửi đơn nhận nuôi.','identity',uid('event'));break;}
 case 'PET_SAVE':{auth('pet');const existing=p.id?ownedPet(p.id):null;need(!existing||existing.status!=='ADOPTED','Hồ sơ đã bàn giao được giữ nguyên lịch sử.');need(['DOG','CAT'].includes(p.species),'Chỉ hỗ trợ chó và mèo.');const data={...p,name:text(p,'name','tên thú cưng',100),title:text(p,'title','tiêu đề',180),intro:text(p,'intro','giới thiệu'),city:text(p,'city','khu vực'),fee:Number(p.fee||0),weight:Number(p.weight||0),ageMonths:Number(p.ageMonths||0),ageRecordedAt:new Date(nowOf(s)).toISOString().slice(0,10)};need(data.fee>=0&&data.ageMonths>=0&&data.weight>=0,'Phí, cân nặng và tuổi không được âm.');delete data.id;delete data.posterId;delete data.approval;delete data.status;delete data.visibility;delete data.deletedAt;if(existing)mutate('PET',existing,{...data,approval:existing.approval==='APPROVED'?'PENDING_APPROVAL':existing.approval});else{const pet={...data,id:uid('p'),posterId:actor.id,approval:'DRAFT',status:'WAITING',visibility:'PUBLIC',featured:false,createdAt:stamp(s),updatedAt:stamp(s),deletedAt:null};s.pets.push(pet);result=pet.id;log(s,actor,'CREATE_PET','PET',pet.id,null,pet);}break;}
 case 'PET_SUBMIT':{auth('pet');const pet=ownedPet(p.id);need(['DRAFT','REJECTED'].includes(pet.approval),'Bài đã được gửi hoặc duyệt.');need(pet.cover&&pet.health?.current&&pet.intro&&pet.city,'Bài cần có ảnh cover, sức khỏe, giới thiệu và khu vực.');mutate('PET',pet,{approval:'PENDING_APPROVAL',rejectionReason:''});admins(s).forEach(u=>notify(s,u.id,'PET_REVIEW','Có bài thú cưng chờ duyệt',pet.name,'admin/pets',uid('event')));break;}
 case 'PET_REVIEW':{admin();const pet=ownedPet(p.id);need(pet.approval==='PENDING_APPROVAL','Bài không còn chờ duyệt.');need(['APPROVED','REJECTED'].includes(p.status),'Trạng thái chưa hợp lệ.');if(p.status==='REJECTED')text(p,'reason','lý do từ chối');mutate('PET',pet,{approval:p.status,rejectionReason:p.reason||'',reviewedBy:actor.id,reviewedAt:stamp(s)});notify(s,pet.posterId,'PET_REVIEW',p.status==='APPROVED'?'Bài đăng đã được duyệt':'Bài đăng cần chỉnh sửa',p.reason||`${pet.name} đã sẵn sàng gặp mọi người.`,`pet/${pet.id}`,uid('event'));break;}
 case 'PET_STATE':{auth('pet');const pet=ownedPet(p.id);need(pet.status!=='ADOPTED','Không đổi trạng thái của Pet đã bàn giao.');need(['WAITING','PAUSED','COMING_SOON'].includes(p.status),'Trạng thái này được tạo từ quy trình nhận nuôi.');mutate('PET',pet,{status:p.status});if(p.status==='WAITING')recalcPet(s,pet);break;}
 case 'PET_VISIBILITY':{admin();const pet=ownedPet(p.id);mutate('PET',pet,{visibility:pet.visibility==='HIDDEN'?'PUBLIC':'HIDDEN'});break;}
 case 'PET_FEATURED':{admin();const pet=ownedPet(p.id);mutate('PET',pet,{featured:!pet.featured});break;}
 case 'PET_DELETE':{auth('pet');const pet=ownedPet(p.id);need(!s.applications.some(a=>a.petId===pet.id&&['PENDING','INTERVIEW','BACKUP','APPROVED'].includes(a.status)),'Hãy giải quyết các hồ sơ còn hiệu lực trước khi xóa bài.');mutate('PET',pet,{deletedAt:stamp(s)});break;}
 case 'APPLICATION_SUBMIT':{auth('application');const pet=s.pets.find(x=>x.id===p.petId);need(!canApply(s,actor,pet),canApply(s,actor,pet));need(declarations.every(([k])=>p.declarations?.[k]===true),'Bạn cần đồng ý đầy đủ tám cam kết.');need(p.care?.petsAllowed==='YES','Nơi ở phải cho phép nuôi thú cưng.');need(Number(p.care.householdSize)>0,'Số người sống cùng phải lớn hơn 0.');for(const k of ['housing','livingArea','experience','otherPets','careTime','caregiver'])need(p.care[k],`Hãy bổ sung thông tin chăm sóc: ${k}.`);if(p.care.experience==='YES')need(p.care.experienceSpecies&&p.care.experienceDuration,'Hãy bổ sung loài và thời gian đã nuôi.');if(p.care.otherPets==='YES')need(Number(p.care.otherPetCount)>0&&p.care.otherPetSpecies,'Hãy bổ sung thú cưng hiện có.');const snap={name:actor.name,email:actor.email,phone:actor.phone,dob:actor.dob,occupation:actor.occupation,city:actor.city,address:p.address?text(p,'address','địa chỉ'):actor.address};const a={id:uid('a'),petId:pet.id,applicantId:actor.id,status:'PENDING',isPrimary:false,reason:text(p,'reason','lý do nhận nuôi'),choiceReason:text(p,'choiceReason','lý do chọn bạn nhỏ này'),snapshot:snap,petSnapshot:structuredClone(pet),care:p.care,declarations:p.declarations,acceptedAt:stamp(s),createdAt:stamp(s),updatedAt:stamp(s)};s.applications.push(a);pet.status='UNDER_REVIEW';result=a.id;log(s,actor,'CREATE_APPLICATION','APPLICATION',a.id,null,a);notify(s,pet.posterId,'APPLICATION',`${pet.name} có hồ sơ mới`,`${actor.name} muốn nhận nuôi ${pet.name}.`,`application/${a.id}`,uid('event'));break;}
 case 'APPLICATION_REVIEW':{auth('application');const a=app(p.id);poster(a);need(['PENDING','INTERVIEW','BACKUP'].includes(a.status),'Đơn đã kết thúc.');need(['INTERVIEW','REJECTED','BACKUP'].includes(p.status),'Trạng thái xét duyệt không hợp lệ.');const pet=s.pets.find(x=>x.id===a.petId);need(pet.status!=='ADOPTED','Thú cưng đã được bàn giao.');if(p.status==='REJECTED')text(p,'reason','lý do từ chối');if(p.status==='INTERVIEW'){need(!s.applications.some(x=>x.petId===a.petId&&x.id!==a.id&&x.isPrimary&&['INTERVIEW','APPROVED'].includes(x.status)),'Đang có một hồ sơ chính. Hãy xử lý hồ sơ đó trước.');for(const other of s.applications.filter(x=>x.petId===a.petId&&x.id!==a.id&&x.status==='PENDING')){other.status='BACKUP';other.updatedAt=stamp(s);log(s,actor,'SET_BACKUP','APPLICATION',other.id,null,other);}}mutate('APPLICATION',a,{status:p.status,isPrimary:p.status==='INTERVIEW',rejectionReason:p.reason||''});if(p.status==='REJECTED'||p.status==='BACKUP')cancelRelated(s,a);recalcPet(s,pet);notifyParties(s,a,p.status,p.status==='INTERVIEW'?`${pet.name} muốn gặp bạn`:'Hồ sơ nhận nuôi được cập nhật',p.reason||'Hãy xem bước tiếp theo trong hồ sơ.',`application/${a.id}`);break;}
 case 'APPLICATION_CANCEL':{auth('application');const a=app(p.id);need(a.applicantId===actor.id,'Chỉ người gửi được hủy đơn.');need(['PENDING','INTERVIEW','BACKUP'].includes(a.status),'Không thể hủy hồ sơ đã kết thúc.');mutate('APPLICATION',a,{status:'CANCELLED',isPrimary:false,cancelReason:p.reason||'',cancelledAt:stamp(s)});cancelRelated(s,a);recalcPet(s,s.pets.find(x=>x.id===a.petId));notifyParties(s,a,'CANCELLED','Đơn nhận nuôi đã được hủy',p.reason||'Người gửi đã hủy hồ sơ.',`application/${a.id}`);break;}
 case 'APPOINTMENT_SAVE':{auth('appointment');const a=app(p.applicationId);need(a.status==='INTERVIEW','Chỉ tạo lịch sau khi hồ sơ được chọn phỏng vấn.');need(p.startsAt&&+new Date(p.startsAt)>nowOf(s),'Thời gian hẹn cần ở tương lai.');need(p.type==='ONLINE'?p.url:p.location,'Vui lòng nhập địa điểm hoặc liên kết gặp mặt.');if(p.url)need(/^https?:\/\//i.test(p.url),'Liên kết phải bắt đầu bằng http:// hoặc https://.');const old=p.id?s.appointments.find(x=>x.id===p.id&&x.applicationId===a.id):null;need(!p.id||old,'Không tìm thấy lịch hẹn.');need(!old||old.status==='SCHEDULED','Chỉ đổi lịch còn hiệu lực.');need(old||!s.appointments.some(x=>x.applicationId===a.id&&x.status==='SCHEDULED'),'Đã có lịch hẹn đang chờ.');const data={applicationId:a.id,startsAt:new Date(p.startsAt).toISOString(),endsAt:p.endsAt?new Date(p.endsAt).toISOString():null,type:p.type,location:p.location||'',url:p.url||'',notes:p.notes||'',status:'SCHEDULED',createdBy:old?.createdBy||actor.id};if(data.endsAt)need(+new Date(data.endsAt)>+new Date(data.startsAt),'Giờ kết thúc phải sau giờ bắt đầu.');if(old)mutate('APPOINTMENT',old,data);else{const ap={...data,id:uid('ap'),createdAt:stamp(s)};s.appointments.push(ap);result=ap.id;log(s,actor,type,'APPOINTMENT',ap.id,null,ap);}notifyParties(s,a,'APPOINTMENT','Lịch hẹn được cập nhật',`${p.location||'Gặp trực tuyến'} · ${new Date(p.startsAt).toLocaleString('vi-VN')}`,`application/${a.id}`);break;}
 case 'APPOINTMENT_STATUS':{auth('appointment');const ap=s.appointments.find(x=>x.id===p.id);need(ap,'Không tìm thấy lịch hẹn.');const a=app(ap.applicationId);need(a.status==='INTERVIEW'&&ap.status==='SCHEDULED','Lịch hẹn không còn hiệu lực.');need(['CANCELLED','COMPLETED','NO_SHOW'].includes(p.status),'Trạng thái không hợp lệ.');if(p.status==='COMPLETED'){poster(a);text(p,'result','kết quả phỏng vấn');need(['PROCEED','REJECT','NEED_MORE_INFO'].includes(p.decision),'Hãy chọn kết luận.');}mutate('APPOINTMENT',ap,{status:p.status,result:p.result||'',decision:p.decision||''});notifyParties(s,a,'APPOINTMENT','Lịch hẹn đã thay đổi',p.result||'Hãy kiểm tra lại lịch gặp mặt.',`application/${a.id}`);break;}
 case 'COMMITMENT_CREATE':{auth('commitment');const a=app(p.applicationId);need(a.status==='INTERVIEW','Hồ sơ chưa ở bước phỏng vấn.');need(s.appointments.some(ap=>ap.applicationId===a.id&&ap.status==='COMPLETED'&&ap.decision==='PROCEED'),'Cần hoàn tất phỏng vấn với kết luận cho phép bàn giao.');need(!s.commitments.some(c=>c.applicationId===a.id&&c.status!=='CANCELLED'),'Đã có cam kết hiện hành.');const c={id:uid('cm'),applicationId:a.id,content:text(p,'content','nội dung cam kết'),status:'PENDING',version:1,applicantSignedAt:null,posterSignedAt:null,createdAt:stamp(s)};s.commitments.push(c);result=c.id;notifyParties(s,a,'COMMITMENT','Cam kết đang chờ xác nhận','Hai bên cần đọc và xác nhận cam kết trước bàn giao.',`application/${a.id}`);log(s,actor,type,'COMMITMENT',c.id,null,c);break;}
 case 'COMMITMENT_SIGN':{auth('commitment');const c=s.commitments.find(x=>x.id===p.id);need(c&&c.status==='PENDING','Cam kết không còn chờ ký.');const a=app(c.applicationId),pet=s.pets.find(x=>x.id===a.petId);need([a.applicantId,pet.posterId].includes(actor.id),'Admin không ký thay hai bên.');if(actor.id===a.applicantId)c.applicantSignedAt=stamp(s);else c.posterSignedAt=stamp(s);if(c.applicantSignedAt&&c.posterSignedAt)c.status='SIGNED';log(s,actor,type,'COMMITMENT',c.id,null,c);break;}
 case 'COMMITMENT_CANCEL':{auth('commitment');const c=s.commitments.find(x=>x.id===p.id);need(c,'Không tìm thấy cam kết.');app(c.applicationId);need(!s.handovers.some(h=>h.applicationId===c.applicationId&&h.status==='COMPLETED'),'Bàn giao đã hoàn tất.');mutate('COMMITMENT',c,{status:'CANCELLED',reason:text(p,'reason','lý do hủy'),cancelledAt:stamp(s)});for(const h of s.handovers.filter(h=>h.commitmentId===c.id))h.status='CANCELLED';break;}
 case 'HANDOVER_CREATE':{auth('handover');const a=app(p.applicationId),c=s.commitments.find(x=>x.applicationId===a.id&&x.status==='SIGNED');need(c,'Cần cam kết đã được cả hai bên ký.');need(a.status==='INTERVIEW'&&a.isPrimary,'Cần hồ sơ chính ở bước phỏng vấn.');need(!s.handovers.some(h=>h.applicationId===a.id&&h.status!=='CANCELLED'),'Đã có biên bản bàn giao.');const h={id:uid('ho'),applicationId:a.id,commitmentId:c.id,status:'PENDING',location:text(p,'location','địa điểm bàn giao'),scheduledAt:p.scheduledAt||stamp(s),notes:p.notes||'',posterConfirmedAt:null,applicantConfirmedAt:null,completedAt:null,createdAt:stamp(s)};s.handovers.push(h);result=h.id;log(s,actor,type,'HANDOVER',h.id,null,h);break;}
 case 'HANDOVER_CONFIRM':{auth('handover');const h=s.handovers.find(x=>x.id===p.id);need(h&&h.status==='PENDING','Biên bản không còn chờ xác nhận.');const a=app(h.applicationId),pet=s.pets.find(x=>x.id===a.petId),c=s.commitments.find(x=>x.id===h.commitmentId);need(a.status==='INTERVIEW'&&c?.status==='SIGNED'&&pet.status!=='ADOPTED','Hồ sơ/cam kết không còn hợp lệ để bàn giao.');need([a.applicantId,pet.posterId].includes(actor.id),'Admin không xác nhận thay hai bên.');if(actor.id===a.applicantId)h.applicantConfirmedAt=stamp(s);else h.posterConfirmedAt=stamp(s);if(h.applicantConfirmedAt&&h.posterConfirmedAt){h.status='COMPLETED';h.completedAt=stamp(s);a.status='APPROVED';pet.status='ADOPTED';for(const other of s.applications.filter(x=>x.petId===pet.id&&x.id!==a.id&&['PENDING','INTERVIEW','BACKUP'].includes(x.status))){other.status='REJECTED';other.isPrimary=false;other.rejectionReason='Thú cưng đã được bàn giao cho một gia đình phù hợp.';other.updatedAt=stamp(s);cancelRelated(s,other);notifyParties(s,other,'REJECTED','Hồ sơ nhận nuôi đã kết thúc',other.rejectionReason,`application/${other.id}`);}const end=new Date(nowOf(s));end.setMonth(end.getMonth()+s.settings.trackingMonths);s.plans.push({id:uid('pl'),applicationId:a.id,startsAt:stamp(s),endsAt:end.toISOString(),status:'ACTIVE'});notifyParties(s,a,'HANDOVER',`${pet.name} đã có mái ấm mới`,'Bàn giao hoàn tất. Hãy cùng cập nhật hành trình sau nhận nuôi.',`tracking/${a.id}`);log(s,actor,'ADOPTION_COMPLETED','APPLICATION',a.id,null,a);}log(s,actor,type,'HANDOVER',h.id,null,h);break;}
 case 'CHECKIN':{auth('checkin');const a=app(p.applicationId);need(a.applicantId===actor.id&&a.status==='APPROVED','Chỉ người đã nhận nuôi được cập nhật.');const plan=s.plans.find(x=>x.applicationId===a.id);need(plan?.status==='ACTIVE'&&+new Date(plan.endsAt)>nowOf(s),'Kỳ theo dõi đã kết thúc.');need(p.date&&+new Date(p.date)<=nowOf(s),'Ngày cập nhật không được ở tương lai.');need(p.images?.length,'Hãy thêm ít nhất một ảnh tình trạng thú cưng.');const c={id:uid('ci'),applicationId:a.id,userId:actor.id,date:p.date,health:text(p,'health','sức khỏe'),eating:p.eating||'',activity:p.activity||'',mood:p.mood||'',issues:p.issues||'',notes:p.notes||'',images:p.images,createdAt:stamp(s)};s.checkins.push(c);result=c.id;log(s,actor,type,'CHECKIN',c.id,null,{id:c.id,applicationId:a.id});break;}
 case 'INCIDENT':{auth('incident');const a=app(p.applicationId);need(a.applicantId===actor.id&&a.status==='APPROVED','Chỉ người nhận được thông báo sự cố cho ca này.');need(['ILLNESS','INJURY','LOST','DEATH','OTHER'].includes(p.type),'Loại sự cố chưa hợp lệ.');if(p.type==='DEATH')need(p.evidence?.length,'Cần bằng chứng phù hợp cho sự cố thú cưng qua đời.');const i={id:uid('in'),applicationId:a.id,userId:actor.id,type:p.type,description:text(p,'description','mô tả sự cố'),cause:p.cause||'',occurredAt:p.occurredAt||stamp(s),evidence:p.evidence||[],status:'REPORTED',createdAt:stamp(s)};s.incidents.push(i);result=i.id;notifyParties(s,a,'INCIDENT','Có thông báo tình trạng cần quan tâm',p.description,`tracking/${a.id}`);admins(s).forEach(u=>notify(s,u.id,'INCIDENT','Có sự cố sau nhận nuôi','Hãy kiểm tra thông tin liên quan.',`tracking/${a.id}`,uid('event')));log(s,actor,type,'INCIDENT',i.id,null,{id:i.id,type:i.type});break;}
 case 'INCIDENT_REVIEW':{auth('incident');const i=s.incidents.find(x=>x.id===p.id);need(i,'Không tìm thấy sự cố.');const a=app(i.applicationId);poster(a);mutate('INCIDENT',i,{status:p.status==='RESOLVED'?'RESOLVED':'REVIEWING',reviewNotes:text(p,'notes','kết quả kiểm tra'),reviewedBy:actor.id});break;}
 case 'FEEDBACK':{auth('feedback');const a=app(p.applicationId);need(a.applicantId===actor.id&&a.status==='APPROVED','Chỉ người nhận nuôi đã bàn giao được đánh giá.');need(!s.feedback.some(f=>f.applicationId===a.id),'Mỗi đơn chỉ được đánh giá một lần.');need(Number(p.rating)>=1&&Number(p.rating)<=5,'Chọn điểm từ 1 đến 5.');const f={id:uid('fb'),applicationId:a.id,authorId:actor.id,rating:Number(p.rating),comment:p.comment||'',images:p.images||[],createdAt:stamp(s)};s.feedback.push(f);result=f.id;log(s,actor,type,'FEEDBACK',f.id,null,f);break;}
 case 'RESCUE_SAVE':{auth('rescue');const old=p.id?s.rescues.find(x=>x.id===p.id):null;if(old)need(old.authorId===actor.id||actor.role==='ADMIN','Bạn không sở hữu bài cứu trợ.');const data={...p,title:text(p,'title','tiêu đề'),type:text(p,'type','loại hỗ trợ'),content:text(p,'content','nội dung'),address:text(p,'address','địa chỉ nhận'),city:text(p,'city','khu vực'),quantity:Number(p.quantity||0)};need(data.quantity>=0,'Số lượng không được âm.');delete data.id;delete data.authorId;delete data.status;delete data.visibility;if(old)mutate('RESCUE',old,{...data,status:old.status==='APPROVED'?'PENDING_APPROVAL':old.status});else{const r={...data,id:uid('r'),authorId:actor.id,status:'DRAFT',visibility:'PUBLIC',createdAt:stamp(s)};s.rescues.push(r);result=r.id;log(s,actor,type,'RESCUE',r.id,null,r);}break;}
 case 'RESCUE_STATE':{auth('rescue');const r=s.rescues.find(x=>x.id===p.id);need(r,'Không tìm thấy bài cứu trợ.');need(r.authorId===actor.id||actor.role==='ADMIN','Bạn không có quyền quản lý.');if(['APPROVED','REJECTED','COMPLETED','HIDDEN','PUBLIC'].includes(p.status))admin();if(['APPROVED','REJECTED'].includes(p.status))need(r.status==='PENDING_APPROVAL','Bài không còn chờ duyệt.');if(p.status==='REJECTED')text(p,'reason','lý do từ chối');if(p.status==='PENDING_APPROVAL')need(['DRAFT','REJECTED'].includes(r.status),'Bài đã được gửi duyệt.');if(p.status==='COMPLETED')need(r.status==='APPROVED','Chỉ hoàn thành bài đã duyệt.');if(p.status==='CANCELLED')need(!['COMPLETED','CANCELLED'].includes(r.status),'Bài đã kết thúc.');need(['PENDING_APPROVAL','APPROVED','REJECTED','COMPLETED','CANCELLED','HIDDEN','PUBLIC'].includes(p.status),'Trạng thái không hợp lệ.');mutate('RESCUE',r,['HIDDEN','PUBLIC'].includes(p.status)?{visibility:p.status}:{status:p.status,rejectionReason:p.reason||'',completedAt:p.status==='COMPLETED'?stamp(s):r.completedAt});if(p.status==='PENDING_APPROVAL')admins(s).forEach(u=>notify(s,u.id,'RESCUE','Có bài cứu trợ chờ duyệt',r.title,'admin/rescues',uid('event')));else notify(s,r.authorId,'RESCUE','Bài cứu trợ được cập nhật',p.reason||r.title,`rescue/${r.id}`,uid('event'));break;}
 case 'REPORT':{auth('report');need(['USER','PET','RESCUE','CONTENT','BEHAVIOR'].includes(p.targetType),'Đối tượng báo cáo chưa hợp lệ.');need(p.targetId||p.reference,'Cần chọn đối tượng hoặc liên kết nội dung.');const r={id:uid('rp'),reporterId:actor.id,targetType:p.targetType,targetId:p.targetId||'',reference:p.reference||'',applicationId:p.applicationId||'',reason:text(p,'reason','lý do'),description:text(p,'description','nội dung báo cáo'),evidence:p.evidence||[],status:'PENDING',createdAt:stamp(s)};s.reports.push(r);result=r.id;admins(s).forEach(u=>notify(s,u.id,'REPORT','Có báo cáo mới','Một nội dung cần được xem xét.','admin/reports',uid('event')));log(s,actor,type,'REPORT',r.id,null,r);break;}
 case 'REPORT_REVIEW':{admin();const r=s.reports.find(x=>x.id===p.id);need(r,'Không tìm thấy báo cáo.');need(['INVESTIGATING','RESOLVED','REJECTED'].includes(p.status),'Trạng thái không hợp lệ.');if(p.status!=='INVESTIGATING')text(p,'resolution','kết luận hoặc lý do');mutate('REPORT',r,{status:p.status,resolution:p.resolution||'',assignedTo:actor.id,resolvedAt:p.status==='INVESTIGATING'?null:stamp(s)});notify(s,r.reporterId,'REPORT_RESOLVED','Báo cáo của bạn đã được cập nhật',p.resolution||'Quản trị viên đang kiểm tra.','reports',uid('event'));break;}
 case 'MODERATE':{admin();const u=s.users.find(x=>x.id===p.userId);need(u&&u.id!==actor.id&&u.role!=='ADMIN','Không thể áp dụng thao tác này lên quản trị viên.');need(['WARN','RESTRICT','BAN','UNBAN','UNRESTRICT'].includes(p.action),'Hành động không hợp lệ.');const m={id:uid('mo'),userId:u.id,adminId:actor.id,action:p.action,reason:text(p,'reason','lý do xử lý'),reportId:p.reportId||'',scopes:p.scopes||['application','pet','rescue'],startsAt:stamp(s),endsAt:p.endsAt?new Date(p.endsAt).toISOString():null,createdAt:stamp(s)};if(m.endsAt)need(+new Date(m.endsAt)>nowOf(s),'Thời hạn cần ở tương lai.');s.moderation.push(m);if(p.action==='RESTRICT')u.status='RESTRICTED';if(p.action==='BAN')u.status='BANNED';if(p.action==='UNRESTRICT'){s.moderation.filter(x=>x.userId===u.id&&x.action==='RESTRICT').forEach(x=>x.revokedAt=stamp(s));if(u.status!=='BANNED')u.status='ACTIVE';}if(p.action==='UNBAN')u.status=effectiveScopes(s,u).length?'RESTRICTED':'ACTIVE';notify(s,u.id,p.action,'Trạng thái tài khoản được cập nhật',p.reason,'profile',uid('event'));log(s,actor,p.action,'USER',u.id,null,{id:u.id,status:u.status,reason:p.reason});break;}
 case 'NOTIFICATION_READ':{auth('notification');for(const n of s.notifications)if(n.userId===actor.id&&(!p.id||n.id===p.id))n.readAt=stamp(s);break;}
 case 'MESSAGE':{auth('message');const a=app(p.applicationId),pet=s.pets.find(x=>x.id===a.petId);need([a.applicantId,pet.posterId].includes(actor.id),'Chỉ hai bên được gửi tin nhắn.');need(['INTERVIEW','APPROVED'].includes(a.status),'Chat mở khi hồ sơ đã được chọn phỏng vấn.');const m={id:uid('msg'),applicationId:a.id,senderId:actor.id,content:text(p,'content','tin nhắn',2000),createdAt:stamp(s)};s.messages.push(m);const other=actor.id===a.applicantId?pet.posterId:a.applicantId;notify(s,other,'MESSAGE','Bạn có tin nhắn mới',m.content,`application/${a.id}`,uid('event'));result=m.id;break;}
 case 'EXPORT':{admin();const e={id:uid('export'),actorId:actor.id,group:p.group||'overview',filters:p.filters||{},format:'CSV',createdAt:stamp(s)};s.exports.push(e);log(s,actor,'EXPORT_REPORT','EXPORT',e.id,null,{id:e.id,type:e.group});break;}
 case 'CLOCK':{admin();s.clockOffset+=Number(p.days||0)*86400000;need(Number.isFinite(s.clockOffset),'Thời gian không hợp lệ.');break;}
 case 'SETTINGS':{admin();need([2,3].includes(Number(p.trackingMonths)),'Thời gian theo dõi phải là 2 hoặc 3 tháng.');s.settings.trackingMonths=Number(p.trackingMonths);break;}
 default:throw new Error(`Thao tác chưa được hỗ trợ: ${type}`);
 }
 s.revision=(s.revision||0)+1;return {state:s,result};
}

export function runScheduler(state){const s=structuredClone(state);let changed=false;const now=nowOf(s);
 for(const u of s.users.filter(u=>u.status==='RESTRICTED'))if(!effectiveScopes(s,u).length){u.status='ACTIVE';changed=true;}
 for(const pl of s.plans.filter(x=>x.status==='ACTIVE')){
  if(+new Date(pl.endsAt)<=now){pl.status='COMPLETED';changed=true;continue;}
  const a=s.applications.find(x=>x.id===pl.applicationId),pet=s.pets.find(x=>x.id===a?.petId);if(!a||!pet)continue;
  const checks=s.checkins.filter(c=>c.applicationId===a.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const anchor=checks[0]?.createdAt||pl.startsAt,hours=(now-new Date(anchor))/3600000;
  let level=hours>s.settings.warningHours?'WARNING':hours>s.settings.reminderHours?'REMINDER':hours>s.settings.checkinHours?'CHECKIN_DUE':null;
  if(level){const ids=level==='WARNING'?[a.applicantId,pet.posterId,...admins(s).map(u=>u.id)]:[a.applicantId];for(const id of new Set(ids)){const n=s.notifications.length;notify(s,id,level,level==='WARNING'?`Cần liên hệ về ${pet.name}`:`Đến lúc cập nhật về ${pet.name}`,level==='WARNING'?'Đã hơn 3 ngày chưa có cập nhật. Hai bên và quản trị viên cần kiểm tra.':level==='REMINDER'?'Đã hơn 2 ngày chưa cập nhật. Hãy gửi tình trạng mới của bạn nhỏ.':'Hãy ghi lại một ngày của bạn nhỏ.',`tracking/${a.id}`,`${level}:${a.id}:${anchor}:${id}`);changed ||= n!==s.notifications.length;}}
 }
 for(const ap of s.appointments.filter(x=>x.status==='SCHEDULED')){const mins=(+new Date(ap.startsAt)-now)/60000;if(mins<=30&&mins>=-60){const a=s.applications.find(x=>x.id===ap.applicationId),pet=s.pets.find(p=>p.id===a?.petId);if(!a)continue;for(const id of [a.applicantId,pet.posterId]){const n=s.notifications.length;notify(s,id,'APPOINTMENT_DUE','Sắp đến lịch gặp mặt',ap.location||'Cuộc hẹn trực tuyến',`application/${a.id}`,`APPOINTMENT:${ap.id}:${ap.startsAt}:${id}`);changed ||= n!==s.notifications.length;}}}
 if(changed)s.revision=(s.revision||0)+1;return {state:s,changed};
}
