import * as THREE from 'three';
// Deterministic terrain and instanced shore details; no remote asset dependencies.
export function createLandscape(scene){
 let seed=7261;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296;};
 const terrainGeometry=new THREE.PlaneGeometry(720,720,112,112);terrainGeometry.rotateX(-Math.PI/2);const p=terrainGeometry.attributes.position,colors=new Float32Array(p.count*3),c=new THREE.Color();
 for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),r=Math.hypot(x,z),angle=Math.atan2(z,x);const coast=91+18*Math.sin(angle*3)+9*Math.cos(angle*7);const fade=THREE.MathUtils.smoothstep(r,coast,coast+50);const ridges=15+Math.pow(Math.sin(x*.019+Math.cos(z*.013)),2)*24+Math.pow(Math.cos(z*.027+x*.008),2)*24;const h=-7+fade*ridges; p.setY(i,h);c.set(h<0?0x7d8873:h<15?0x4f7055:h<35?0x436653:0x667769);c.multiplyScalar(.87+.13*Math.sin(x*.32+z*.11));colors.set([c.r,c.g,c.b],i*3);}
 terrainGeometry.setAttribute('color',new THREE.BufferAttribute(colors,3));terrainGeometry.computeVertexNormals();const terrain=new THREE.Mesh(terrainGeometry,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));terrain.receiveShadow=true;scene.add(terrain);
 const rockGeo=new THREE.IcosahedronGeometry(1,1),rockMat=new THREE.MeshStandardMaterial({color:0x8e9184,roughness:1}),rocks=new THREE.InstancedMesh(rockGeo,rockMat,220),dummy=new THREE.Object3D();
 for(let i=0;i<220;i++){const a=i/220*Math.PI*2,r=33.7+rand()*1.8;dummy.position.set(Math.cos(a)*r,-2.55+rand()*.5,Math.sin(a)*r*.94);dummy.rotation.set(rand()*3,rand()*3,rand()*3);const scale=.3+rand()*.7;dummy.scale.set(scale*1.5,scale*.8,scale);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);rocks.setColorAt(i,new THREE.Color().setHSL(.12+rand()*.06,.08+rand()*.1,.32+rand()*.2));}rocks.receiveShadow=true;scene.add(rocks);
 // Grass blades are small instanced triangles rather than hundreds of scene meshes.
 const bladeGeo=new THREE.BufferGeometry();bladeGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.05,0,0,.05,0,0,.035,.38,0],3));bladeGeo.computeVertexNormals();
 const grassMaterial=new THREE.MeshStandardMaterial({color:0x607f45,roughness:1,side:THREE.DoubleSide});const blades=new THREE.InstancedMesh(bladeGeo,grassMaterial,2400);
 for(let i=0;i<2400;i++){const a=rand()*Math.PI*2,r=23+rand()*8;dummy.position.set(Math.cos(a)*r,.015,Math.sin(a)*r*.92);dummy.rotation.set(0,rand()*6.28,0);dummy.scale.setScalar(.6+rand()*1.3);dummy.updateMatrix();blades.setMatrixAt(i,dummy.matrix);blades.setColorAt(i,new THREE.Color().setHSL(.22+rand()*.04,.22,.25+rand()*.17));}scene.add(blades);
 const waterUniforms={uTime:{value:0},uNight:{value:0}};
 const waterMaterial=new THREE.ShaderMaterial({uniforms:waterUniforms,side:THREE.DoubleSide,vertexShader:`uniform float uTime;varying vec3 vP;void main(){vec3 p=position;p.y+=sin(p.x*.16+uTime*.6)*.1+cos(p.z*.19-uTime*.45)*.08;vP=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float uTime;uniform float uNight;varying vec3 vP;void main(){vec2 p=vP.xz;float waves=sin(p.x*1.9+sin(p.y*.7)+uTime*.9)*sin(p.y*2.6-uTime*.6);float shimmer=pow(max(0.,waves),14.);float r=length(vec2(p.x,p.y/.94));float shore=exp(-pow((r-35.8)/1.6,2.));float foam=shore*pow(.5+.5*sin(r*10.-uTime*1.5),6.);float dist=clamp(length(p)/270.,0.,1.);vec3 day=mix(vec3(.08,.29,.31),vec3(.43,.61,.62),dist);vec3 night=mix(vec3(.012,.055,.084),vec3(.075,.14,.19),dist);vec3 col=mix(day,night,uNight)+shimmer*mix(.09,.035,uNight)+foam*mix(vec3(.28,.36,.29),vec3(.04,.08,.09),uNight);gl_FragColor=vec4(col,1.);}`});
 const waterGeo=new THREE.PlaneGeometry(820,820,70,70);waterGeo.rotateX(-Math.PI/2);const lake=new THREE.Mesh(waterGeo,waterMaterial);lake.position.y=-3;scene.add(lake);
 // Distant forest: two instanced layers taper into the atmospheric haze.
 const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.22,.35,5,5),new THREE.MeshStandardMaterial({color:0x53594a,roughness:1}),160);
 const canopies=new THREE.InstancedMesh(new THREE.ConeGeometry(2.4,9,7),new THREE.MeshStandardMaterial({color:0x385a48,roughness:1}),160);
 for(let i=0;i<160;i++){const a=rand()*6.283,r=105+rand()*100,x=Math.cos(a)*r,z=Math.sin(a)*r;const coast=91+18*Math.sin(a*3)+9*Math.cos(a*7),fade=THREE.MathUtils.smoothstep(r,coast,coast+50),h=-7+fade*(15+Math.pow(Math.sin(x*.019+Math.cos(z*.013)),2)*24+Math.pow(Math.cos(z*.027+x*.008),2)*24);dummy.position.set(x,h+2,z);dummy.rotation.set(0,rand()*6.28,0);dummy.scale.setScalar(.6+rand()*.8);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=h+6;dummy.updateMatrix();canopies.setMatrixAt(i,dummy.matrix);}scene.add(trunks,canopies);
 return {update(time,night,low){waterUniforms.uTime.value=time;waterUniforms.uNight.value=night?1:0;blades.count=low?900:2400;},water:lake};
}
