const ago=(now,days)=>new Date(now-days*86400000).toISOString();
export const DEMO_PASSWORD='Petcare@123';
export const declarations=[
 ['truthfulInformation','Tôi cung cấp thông tin chính xác.'],['properCare','Tôi chăm sóc thú cưng đúng cách.'],
 ['noSale','Tôi không bán thú cưng.'],['noExchange','Tôi không trao đổi thú cưng.'],
 ['noAbandonment','Tôi không bỏ rơi thú cưng.'],['medicalCare','Tôi đưa thú cưng đi khám khi cần.'],
 ['acceptConditions','Tôi tuân thủ các điều kiện nhận nuôi.'],['allowFollowup','Tôi đồng ý cập nhật và cho phép theo dõi sau nhận nuôi.']
];
export const cities=['TP. Hồ Chí Minh','Hà Nội','Đà Nẵng','Cần Thơ','Đồng Nai','Khác'];
export const supportTypes=['Thức ăn','Nước','Vật dụng','Thuốc','Vật tư y tế','Chăm sóc thú cưng','Hỗ trợ trạm cứu hộ','Nhu cầu khác'];
export const reportReasons=['Lừa đảo','Thông tin giả','Bỏ rơi thú cưng','Vi phạm cam kết','Nội dung không phù hợp','Hành vi đáng ngờ','Khác'];
export function createSeed(now=Date.now()){
 const users=[
 {id:'u-linh',name:'Linh Nguyễn',email:'linh@petcare.demo',phone:'0900000101',dob:'2003-05-18',city:cities[0],address:'Địa chỉ mẫu, TP. Hồ Chí Minh',occupation:'Kỹ sư phần mềm',role:'USER',status:'ACTIVE',verified:'VERIFIED',bio:'Muốn dành một góc nhỏ trong nhà cho một người bạn mới.'},
 {id:'u-mai',name:'Mai Anh',email:'mai@petcare.demo',phone:'0900000102',dob:'1996-08-24',city:cities[0],address:'Điểm nhận nuôi Petcare, TP. Hồ Chí Minh',occupation:'Tình nguyện viên',role:'USER',status:'ACTIVE',verified:'VERIFIED',bio:'Đồng hành cùng các bạn nhỏ tìm mái ấm.'},
 {id:'u-admin',name:'Hoàng An',email:'admin@petcare.demo',phone:'0900000103',dob:'1990-02-14',city:cities[0],address:'Văn phòng Petcare',occupation:'Điều phối viên',role:'ADMIN',status:'ACTIVE',verified:'VERIFIED'},
 {id:'u-thao',name:'Thảo Vy',email:'thao@petcare.demo',phone:'0900000104',dob:'2001-11-12',city:cities[1],address:'Địa chỉ mẫu, Hà Nội',occupation:'Nhân viên văn phòng',role:'USER',status:'ACTIVE',verified:'PENDING'},
 {id:'u-nam',name:'Minh Nam',email:'nam@petcare.demo',phone:'0900000105',dob:'1998-07-09',city:cities[2],address:'Địa chỉ mẫu, Đà Nẵng',occupation:'Thiết kế',role:'USER',status:'RESTRICTED',verified:'FAILED'},
 {id:'u-chi',name:'Quỳnh Chi',email:'chi@petcare.demo',phone:'0900000106',dob:'1994-03-20',city:cities[0],address:'Địa chỉ mẫu, TP. Hồ Chí Minh',occupation:'Giáo viên',role:'USER',status:'ACTIVE',verified:'VERIFIED'}
 ].map((u,i)=>({...u,createdAt:ago(now,70-i*10),lastLoginAt:ago(now,i),termsAcceptedAt:ago(now,70-i*10),passwordHash:null}));
 const basePets=[
 ['p-milo','Milo','DOG','Golden Retriever',18,'MALE','dog-01.jpg','Chàng trai của những buổi chiều đầy nắng.','WAITING'],
 ['p-mochi','Mochi','CAT','Mèo ta',8,'FEMALE','cat-01.jpg','Một cục bông nhỏ, một tiếng rừ rừ thật ấm.','WAITING'],
 ['p-bong','Bông','CAT','Anh lông ngắn',14,'FEMALE','cat-02.jpg','Thích nằm bên cửa sổ và nghe bạn kể chuyện.','WAITING'],
 ['p-lucky','Lucky','DOG','Chó ta',24,'MALE','dog-02.jpg','Đã sẵn sàng cho một hành trình mới cùng bạn.','UNDER_REVIEW'],
 ['p-luna','Luna','CAT','Mèo tam thể',12,'FEMALE','cat-03.jpg','Cô bạn dịu dàng đang đợi một lời chào.','WAITING'],
 ['p-teddy','Teddy','DOG','Labrador',30,'MALE','dog-03.jpg','Năng động, tình cảm và mê những cuộc đi dạo.','WAITING'],
 ['p-sua','Sữa','CAT','Mèo ta',6,'MALE','cat-04.jpg','Bé út tò mò với mọi thứ trong khu vườn.','COMING_SOON'],
 ['p-bun','Bún','DOG','Chó ta',10,'FEMALE','dog-04.jpg','Nhỏ xíu nhưng có một trái tim thật lớn.','PAUSED'],
 ['p-coffee','Coffee','DOG','Chó ta',22,'MALE','dog-02.jpg','Đã tìm được gia đình của mình.','ADOPTED'],
 ['p-miu','Miu','CAT','Mèo ta',16,'FEMALE','cat-01.jpg','Một khởi đầu mới trong ngôi nhà đầy yêu thương.','ADOPTED'],
 ['p-sunny','Sunny','DOG','Golden Retriever',9,'FEMALE','dog-01.jpg','Đang hoàn thiện hồ sơ để chào mọi người.','WAITING'],
 ['p-peach','Peach','CAT','Mèo ta',5,'FEMALE','cat-03.jpg','Bé mèo tìm thấy gần trạm cứu trợ.','WAITING']
 ];
 const pets=basePets.map((p,i)=>({id:p[0],name:p[1],species:p[2],breed:p[3],ageMonths:p[4],ageRecordedAt:ago(now,0).slice(0,10),sex:p[5],cover:`assets/${p[6]}`,images:[`assets/${p[6]}`],videos:[],intro:p[7],status:p[8],approval:i===10?'PENDING_APPROVAL':i===11?'DRAFT':'APPROVED',visibility:'PUBLIC',posterId:i===11?'u-linh':'u-mai',title:`Tìm mái ấm cho ${p[1]}`,birthDate:'',color:i%2?'Trắng / vàng':'Vàng nâu',weight:p[2]==='DOG'?12+i:3.2,size:p[2]==='DOG'?'MEDIUM':'SMALL',city:i===5?cities[2]:cities[0],district:'Khu vực trung tâm',handoverLocation:'Nhà kết nối Petcare',lat:10.7769,lng:106.7009,purpose:'Tìm người nhận nuôi',reason:'Tìm một gia đình phù hợp và gắn bó lâu dài.',adoptionOpenAt:i===6?ago(now,-7).slice(0,10):ago(now,20).slice(0,10),fee:0,currency:'VND',background:'Được chăm sóc bởi các tình nguyện viên tại khu bảo trợ.',history:'Đã kiểm tra sức khỏe trước khi tìm mái ấm.',situation:'Sinh hoạt ổn định, đang được chăm sóc tại Petcare.',wishes:'Một gia đình có thời gian quan tâm và chăm sóc.',notes:'Cần làm quen từ từ với môi trường mới.',health:{current:'Khỏe mạnh',vaccines:'Đã tiêm theo lịch',deworming:'Đã tẩy giun định kỳ',neutered:i>2?'Đã triệt sản':'Chưa triệt sản',conditions:'Không ghi nhận',history:'Không có bệnh nền được ghi nhận',medications:'Không'},personality:{temperament:i%2?'Dịu dàng, tò mò':'Thân thiện, năng động',people:'YES',children:'YES',dogs:'UNKNOWN',cats:p[2]==='CAT'?'YES':'UNKNOWN',habits:'Thích giờ ăn và sinh hoạt đều đặn',likes:p[2]==='DOG'?'Đi dạo, chơi bóng':'Nằm nắng, đồ chơi lông vũ',notes:'Thích được tiếp cận nhẹ nhàng'},conditions:['Đủ 18 tuổi và đã xác minh danh tính','Nơi ở cho phép nuôi thú cưng','Không bán, trao đổi hoặc bỏ rơi','Đồng ý theo dõi trong 3 tháng đầu'],featured:i<3,createdAt:ago(now,30-i*2),updatedAt:ago(now,2),deletedAt:null,rejectionReason:''}));
 const care={housing:'Chung cư',housingOther:'',petsAllowed:'YES',livingArea:'Trong nhà',householdSize:2,children:'NO',allergies:'NO',experience:'YES',experienceSpecies:'Chó, mèo',experienceDuration:'3 năm',otherPets:'NO',otherPetCount:0,otherPetSpecies:'',careTime:'3–4 giờ mỗi ngày',caregiver:'Tôi trực tiếp chăm sóc',food:true,vaccines:true,treatment:true,medicalVisits:true,routineCare:true,travelPlan:'Gửi người thân chăm sóc',businessPlan:'Nhờ người nhà',absencePlan:'Có người ở nhà'};
 const makeApp=(id,petId,userId,status,days)=>({id,petId,applicantId:userId,status,isPrimary:['INTERVIEW','APPROVED'].includes(status),reason:'Muốn chăm sóc một người bạn mới lâu dài.',choiceReason:'Tính cách phù hợp với gia đình mình.',snapshot:structuredClone(users.find(u=>u.id===userId)),petSnapshot:structuredClone(pets.find(p=>p.id===petId)),care:structuredClone(care),declarations:Object.fromEntries(declarations.map(([k])=>[k,true])),acceptedAt:ago(now,days),createdAt:ago(now,days),updatedAt:ago(now,days-1),rejectionReason:'',cancelReason:''});
 const applications=[makeApp('a-lucky','p-lucky','u-linh','INTERVIEW',4),makeApp('a-backup','p-lucky','u-chi','BACKUP',3),makeApp('a-coffee','p-coffee','u-linh','APPROVED',12),makeApp('a-miu','p-miu','u-chi','APPROVED',35)];
 return {version:1,revision:0,clockOffset:0,settings:{trackingMonths:3,checkinHours:24,reminderHours:48,warningHours:72},users,pets,applications,
 identities:[{id:'iv-thao',userId:'u-thao',fullName:'Thảo Vy',citizenId:'DEMO-0104',documents:[],status:'PENDING',createdAt:ago(now,1),reason:''},{id:'iv-nam',userId:'u-nam',fullName:'Minh Nam',citizenId:'DEMO-0105',documents:[],status:'FAILED',createdAt:ago(now,3),reason:'Hình ảnh mẫu chưa đủ rõ.'}],
 appointments:[{id:'ap-lucky',applicationId:'a-lucky',createdBy:'u-mai',startsAt:ago(now,-1),endsAt:ago(now,-1-.04),type:'IN_PERSON',location:'Nhà kết nối, khu Petcare',url:'',status:'SCHEDULED',notes:'Hai bên gặp Lucky và trao đổi điều kiện chăm sóc.',result:'',decision:''}],
 commitments:[{id:'cm-coffee',applicationId:'a-coffee',status:'SIGNED',applicantSignedAt:ago(now,11),posterSignedAt:ago(now,11),content:'Chăm sóc đúng cách, không bỏ rơi, cho phép hậu kiểm trong 3 tháng.',version:1,createdAt:ago(now,11)},{id:'cm-miu',applicationId:'a-miu',status:'SIGNED',applicantSignedAt:ago(now,34),posterSignedAt:ago(now,34),content:'Chăm sóc đúng cách và cập nhật hậu kiểm.',version:1,createdAt:ago(now,34)}],
 handovers:[{id:'ho-coffee',applicationId:'a-coffee',commitmentId:'cm-coffee',status:'COMPLETED',location:'Nhà kết nối Petcare',posterConfirmedAt:ago(now,10),applicantConfirmedAt:ago(now,10),completedAt:ago(now,10),notes:'Coffee đã đến nhà mới.',createdAt:ago(now,10)},{id:'ho-miu',applicationId:'a-miu',commitmentId:'cm-miu',status:'COMPLETED',location:'Nhà kết nối Petcare',posterConfirmedAt:ago(now,33),applicantConfirmedAt:ago(now,33),completedAt:ago(now,33),notes:'Miu đã làm quen với gia đình.',createdAt:ago(now,33)}],
 plans:[{id:'pl-coffee',applicationId:'a-coffee',startsAt:ago(now,10),endsAt:ago(now,-80),status:'ACTIVE'},{id:'pl-miu',applicationId:'a-miu',startsAt:ago(now,33),endsAt:ago(now,-57),status:'ACTIVE'}],
 checkins:[{id:'ci-coffee',applicationId:'a-coffee',userId:'u-linh',date:ago(now,1).slice(0,10),health:'Khỏe mạnh',eating:'Ăn hết khẩu phần, uống đủ nước',activity:'Đi dạo buổi sáng và chiều',mood:'Vui vẻ, đã quen nhà mới',issues:'Không',notes:'Coffee rất thích chiếc đệm mới.',images:['assets/dog-02.jpg'],createdAt:ago(now,1)},{id:'ci-miu',applicationId:'a-miu',userId:'u-chi',date:ago(now,4).slice(0,10),health:'Khỏe mạnh',eating:'Ăn tốt',activity:'Chơi đùa trong nhà',mood:'Thoải mái',issues:'Không',notes:'',images:['assets/cat-01.jpg'],createdAt:ago(now,4)}],
 incidents:[],feedback:[{id:'fb-miu',applicationId:'a-miu',authorId:'u-chi',rating:5,comment:'Các bạn tình nguyện viên hỗ trợ rất tận tâm. Miu đã quen với ngôi nhà mới.',images:[],createdAt:ago(now,30)}],
 rescues:[
 {id:'r-food',authorId:'u-mai',title:'Thêm một bữa no cho 25 bạn nhỏ',type:'Thức ăn',content:'Trạm đang cần thức ăn khô cho chó và mèo trong tuần này. Bạn có thể mang trực tiếp đến khu tiếp nhận. Mọi vật phẩm đều được ghi nhận tại trạm.',quantity:50,unit:'kg',priority:'HIGH',neededBy:ago(now,-5).slice(0,10),contactName:'Mai Anh',phone:'0900000102',city:cities[0],address:'Khu tiếp nhận Petcare, điểm hẹn công cộng',lat:10.7769,lng:106.7009,images:['assets/dog-03.jpg'],videos:[],notes:'Ưu tiên bao bì còn nguyên, còn hạn sử dụng.',status:'APPROVED',visibility:'PUBLIC',createdAt:ago(now,3)},
 {id:'r-blanket',authorId:'u-mai',title:'Góp một chiếc chăn, gửi một chút ấm',type:'Vật dụng',content:'Cần chăn mỏng, khăn sạch và nệm nhỏ cho những bạn mới được tiếp nhận.',quantity:20,unit:'chiếc',priority:'NORMAL',neededBy:ago(now,-10).slice(0,10),contactName:'Mai Anh',phone:'0900000102',city:cities[0],address:'Nhà cộng đồng Petcare',lat:10.78,lng:106.70,images:['assets/cat-02.jpg'],videos:[],notes:'Vật dụng đã giặt sạch.',status:'APPROVED',visibility:'PUBLIC',createdAt:ago(now,5)},
 {id:'r-care',authorId:'u-thao',title:'Cần bạn đồng hành chăm mèo cuối tuần',type:'Chăm sóc thú cưng',content:'Tìm người hỗ trợ cho ăn và vệ sinh khu mèo tại trạm.',quantity:3,unit:'người',priority:'NORMAL',neededBy:ago(now,-7).slice(0,10),contactName:'Thảo Vy',phone:'0900000104',city:cities[1],address:'Điểm sinh hoạt cộng đồng mẫu, Hà Nội',images:['assets/cat-03.jpg'],videos:[],status:'PENDING_APPROVAL',visibility:'PUBLIC',createdAt:ago(now,1)},
 {id:'r-done',authorId:'u-mai',title:'Đã đủ thuốc và vật tư cho tháng này',type:'Vật tư y tế',content:'Cảm ơn các bạn đã đồng hành cùng khu chăm sóc.',quantity:10,unit:'bộ',priority:'NORMAL',contactName:'Mai Anh',phone:'0900000102',city:cities[0],address:'Điểm tiếp nhận Petcare',images:['assets/dog-04.jpg'],videos:[],status:'COMPLETED',visibility:'PUBLIC',createdAt:ago(now,25),completedAt:ago(now,15)}],
 reports:[{id:'rp-1',reporterId:'u-chi',targetType:'USER',targetId:'u-nam',reason:'Thông tin giả',description:'Thông tin liên hệ trong hồ sơ cần được xác minh lại. Đây là tình huống mẫu để trải nghiệm quy trình xử lý.',evidence:[],status:'INVESTIGATING',assignedTo:'u-admin',resolution:'',createdAt:ago(now,3),updatedAt:ago(now,2)}],
 moderation:[{id:'mod-1',userId:'u-nam',adminId:'u-admin',reportId:'rp-1',action:'RESTRICT',reason:'Đợi bổ sung thông tin xác minh.',scopes:['application','pet','rescue'],startsAt:ago(now,2),endsAt:ago(now,-5),createdAt:ago(now,2)}],
 notifications:[{id:'n-1',userId:'u-linh',type:'INTERVIEW',title:'Lucky muốn gặp bạn',body:'Hồ sơ của bạn đã được chọn. Hãy xem lịch gặp mặt để cùng chuẩn bị nhé.',route:'application/a-lucky',readAt:null,createdAt:ago(now,2),dedupeKey:'seed-interview'},{id:'n-2',userId:'u-mai',type:'APPLICATION',title:'Có một lời chào mới gửi tới Lucky',body:'Linh vừa gửi hồ sơ nhận nuôi.',route:'application/a-lucky',readAt:null,createdAt:ago(now,4),dedupeKey:'seed-application'}],
 messages:[{id:'msg-1',applicationId:'a-lucky',senderId:'u-mai',content:'Chào Linh! Bạn có thể đến gặp Lucky vào ngày mai được không?',createdAt:ago(now,1)}],
 logs:[{id:'log-seed',actorId:null,action:'DEMO_INITIALIZED',entity:'SYSTEM',entityId:'demo',oldValue:null,newValue:{dataset:'Dữ liệu mẫu PETCARE HUB'},createdAt:ago(now,0)}],exports:[]};
}
