export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon=name=>`<i data-lucide="${esc(name)}" aria-hidden="true"></i>`;
export const date=(v,full=false)=>v?new Intl.DateTimeFormat('vi-VN',full?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'medium'}).format(new Date(v)):'Chưa có';
export const localInputDate=v=>{const d=new Date(v||Date.now());return new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export const initials=name=>(name||'Khách').split(' ').slice(-2).map(s=>s[0]).join('').toUpperCase();
const statusLabels={WAITING:'Tìm mái ấm',UNDER_REVIEW:'Đang xét hồ sơ',ADOPTED:'Đã có gia đình',PAUSED:'Tạm dừng',COMING_SOON:'Sắp mở nhận nuôi',DRAFT:'Bản nháp',PENDING_APPROVAL:'Chờ duyệt',APPROVED:'Đã duyệt',REJECTED:'Từ chối',PENDING:'Chờ xem xét',INTERVIEW:'Phỏng vấn',BACKUP:'Dự phòng',CANCELLED:'Đã hủy',COMPLETED:'Hoàn tất',SIGNED:'Đã ký đủ',VERIFIED:'Đã xác minh',UNVERIFIED:'Chưa xác minh',FAILED:'Cần bổ sung',ACTIVE:'Hoạt động',RESTRICTED:'Hạn chế',BANNED:'Đã khóa',SCHEDULED:'Đã lên lịch',NO_SHOW:'Vắng mặt',REPORTED:'Đã thông báo',REVIEWING:'Đang kiểm tra',RESOLVED:'Đã giải quyết',INVESTIGATING:'Đang điều tra',PUBLIC:'Công khai',HIDDEN:'Đã ẩn',HIGH:'Ưu tiên cao',NORMAL:'Thông thường',URGENT:'Khẩn cấp',WARN:'Cảnh cáo',BAN:'Khóa tài khoản',RESTRICT:'Hạn chế',UNBAN:'Mở khóa',UNRESTRICT:'Gỡ hạn chế',ILLNESS:'Bị bệnh',INJURY:'Bị thương',LOST:'Bị mất',DEATH:'Qua đời',OTHER:'Sự cố khác',PROCEED:'Có thể bàn giao',NEED_MORE_INFO:'Cần trao đổi thêm'};
export const label=v=>statusLabels[v]||v;
export const badge=(v,custom)=>`<span class="badge ${['VERIFIED','APPROVED','SIGNED','COMPLETED','ADOPTED','ACTIVE','RESOLVED','WAITING'].includes(v)?'green':['REJECTED','BANNED','FAILED','URGENT','DEATH'].includes(v)?'red':['PENDING','PENDING_APPROVAL','UNDER_REVIEW','INTERVIEW','WARNING','HIGH','RESTRICTED','INVESTIGATING'].includes(v)?'amber':'gray'}">${esc(custom||label(v))}</span>`;
export const btn=(title,action='',extra='',style='secondary')=>`<button type="button" class="btn ${style}" ${action?`data-action="${esc(action)}"`:''} ${extra}>${title}</button>`;
export const input=(title,name,value='',opts={})=>`<label class="field ${opts.wide?'wide':''}"><span>${esc(title)}${opts.required?' <b>*</b>':''}</span><input name="${esc(name)}" type="${opts.type||'text'}" value="${esc(value)}" ${opts.required?'required':''} ${opts.readonly?'readonly':''} ${opts.min!==undefined?`min="${esc(opts.min)}"`:''} ${opts.max!==undefined?`max="${esc(opts.max)}"`:''} ${opts.step?`step="${esc(opts.step)}"`:''} ${opts.placeholder?`placeholder="${esc(opts.placeholder)}"`:''} ${opts.autocomplete?`autocomplete="${esc(opts.autocomplete)}"`:''} maxlength="${opts.maxlength||5000}">${opts.hint?`<small>${esc(opts.hint)}</small>`:''}</label>`;
export const textarea=(title,name,value='',opts={})=>`<label class="field ${opts.wide===false?'':'wide'}"><span>${esc(title)}${opts.required?' <b>*</b>':''}</span><textarea name="${esc(name)}" rows="${opts.rows||3}" ${opts.required?'required':''} maxlength="${opts.maxlength||5000}" placeholder="${esc(opts.placeholder||'')}">${esc(value)}</textarea>${opts.hint?`<small>${esc(opts.hint)}</small>`:''}</label>`;
export const select=(title,name,value,options,opts={})=>`<label class="field ${opts.wide?'wide':''}"><span>${esc(title)}${opts.required?' <b>*</b>':''}</span><select name="${esc(name)}" ${opts.required?'required':''}>${opts.empty!==false?'<option value="">Chọn…</option>':''}${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;
export const check=(title,name,checked=false)=>`<label class="check-field"><input type="checkbox" name="${esc(name)}" ${checked?'checked':''}><span>${esc(title)}</span></label>`;
export const upload=(title,name,existing=[],opts={})=>`<div class="field wide"><span>${esc(title)}${opts.required?' <b>*</b>':''}</span><div class="upload-box">${icon('upload-cloud')}<div><b>Chọn tệp từ máy của bạn</b><span>${opts.video?'Ảnh hoặc video':'Ảnh JPG, PNG, WebP'} · tối đa 12 MB / tệp</span></div><input type="file" name="${esc(name)}" accept="${opts.accept|| (opts.video?'image/*,video/*':'image/*')}" ${opts.single?'':'multiple'} ${opts.required&&!existing.length?'required':''}></div>${existing.length?`<div class="upload-existing">${existing.map((f,i)=>`<label>${media(f,'Tệp đã lưu','upload-thumb')}<input type="checkbox" name="remove_${name}_${i}"> Bỏ tệp ${i+1}</label>`).join('')}</div>`:''}<input type="hidden" name="existing_${esc(name)}" value="${esc(JSON.stringify(existing))}"></div>`;
export const media=(src,alt='',className='',extra='')=>{const local=src?.startsWith('local:');return `<img ${local?`data-media="${esc(src)}"`:`src="${esc(src||'assets/dog-01.jpg')}"`} alt="${esc(alt)}" class="${esc(className)}" loading="lazy" ${extra}>`;};
export const fileLinks=files=>(files||[]).map((f,i)=>`<a class="file-link" ${f.startsWith('local:')?`data-media="${esc(f)}"`:`href="${esc(f)}"`} target="_blank" rel="noopener">${icon('paperclip')} Tệp ${i+1}</a>`).join('');
export const empty=(title,description='',action='')=>`<div class="empty">${icon('sprout')}<h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`;
export const callout=(message,tone='info')=>`<div class="callout ${tone}">${icon(tone==='error'?'circle-alert':tone==='success'?'circle-check':'info')}<span>${message}</span></div>`;
export const card=(title,content,extra='')=>`<section class="section-card"><div class="section-heading"><h3>${title}</h3>${extra}</div>${content}</section>`;
export const fieldset=(title,fields,desc='')=>`<fieldset class="form-section"><legend>${esc(title)}</legend>${desc?`<p class="muted">${esc(desc)}</p>`:''}<div class="form-grid">${fields}</div></fieldset>`;
export const kv=rows=>`<dl class="key-values">${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v??'Chưa cung cấp')}</dd></div>`).join('')}</dl>`;
export const person=u=>`<span class="person"><span class="avatar">${initials(u?.name)}</span><span><b>${esc(u?.name||'Người dùng')}</b><small>${esc(u?.occupation||'Thành viên Petcare')}</small></span></span>`;
export const hidden=(name,value)=>`<input type="hidden" name="${esc(name)}" value="${esc(value)}">`;
export const formEnd=(text='Lưu thay đổi')=>`<div class="form-footer"><p class="form-error" role="alert"></p><button class="btn dark" type="submit">${esc(text)} ${icon('arrow-right')}</button></div></form>`;
export const titleBar=(kicker,title,desc='',action='')=>`<div class="page-heading"><div><span class="eyebrow">${esc(kicker)}</span><h2>${esc(title)}</h2>${desc?`<p>${esc(desc)}</p>`:''}</div>${action}</div>`;
export const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">${empty('Chưa có dữ liệu phù hợp')}</td></tr>`}</tbody></table></div>`;
export function toast(message,tone='success'){const el=document.createElement('div');el.className=`toast ${tone}`;el.textContent=message;document.getElementById('toasts').append(el);setTimeout(()=>el.remove(),5000);}
export function openModal(title,html,wide=false){const dialog=document.getElementById('modal');dialog.classList.toggle('wide-modal',wide);document.getElementById('modal-content').innerHTML=`<header class="modal-header"><h2>${esc(title)}</h2><button type="button" class="icon-btn" data-action="close-modal" aria-label="Đóng">${icon('x')}</button></header><div class="modal-body">${html}</div>`;if(!dialog.open)dialog.showModal();window.lucide?.createIcons();}
export function closeModal(){document.getElementById('modal').close();}
export function safeCSV(rows){return '\ufeff'+rows.map(row=>row.map(value=>{let v=String(value??'');if(/^[=+@\-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
export function download(name,data,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
